wandb_version: 1

epochs:
  desc: null
  value: 30
time_step:
  desc: null
  value: 16
classes:
  desc: null
  value: 11
batch_size:
  desc: null
  value: 8
learning_rate:
  desc: null
  value: 0.1
dataset:
  desc: null
  value: DVS_Gesture_dataset
architecture:
  desc: null
  value: DVS_SNN
_wandb:
  desc: null
  value:
    python_version: 3.11.2
    cli_version: 0.15.4
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1688154562.165504
    t:
      1:
      - 1
      - 5
      - 41
      - 53
      - 55
      2:
      - 1
      - 5
      - 41
      - 53
      - 55
      3:
      - 13
      - 16
      - 23
      4: 3.11.2
      5: 0.15.4
      8:
      - 1
      - 4
      - 5
